### PR TITLE
Update admin records around Istanbul

### LINKED ISSUE #1737: Update neighbourhoods of Istanbul, Turkey
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [ ] **Deprecate / supersede** WOF features
- [ ] **Draft review**
- [ ] **Draft revisions** based on review comments
- [ ] **Final review**
- [ ] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

### PR DESCRIPTION
**Pull request by stepps00**
This PR will fix https://github.com/whosonfirst-data/whosonfirst-data/issues/1737.

To do:

- [x] Update neighbourhood records
- [x] Add new neighbourhood records
- [x] Update locality record
- [x] Update county records
- [x] Validate changes and geometries
- [x] PIP branch

### CODE REVIEW

**Comment by stepps00** [comment]
Cleaned up county shapes
Screenshot 2023-03-01 at 2 59 38 PM

Updated neighbourhood records
Screenshot 2023-03-01 at 2 59 18 PM

New locality extent
Screenshot 2023-03-01 at 2 57 39 PM

**Comment by stepps00** [comment]
The most recent commit includes all of the PIP work needed for this PR. The geojson files and properties have been validated, too.

cc @nvkelso we looked at this together, so I think this can be merged. Good to go?

**Comment by stepps00** [comment]
**Number of records updated**: 1760

**Review by nvkelso — APPROVED** [review]
Wow, huge improvement!

**Open question:** I like what you've done for the sea water, but what should we do for the land water? There are several large lakes that are being overlapped with neighbourhoods now, but in Seattle we provided the lakes there as separate records?

> Number of records updated: 1760

This total is good, and looking at the diff I wonder if we could get more sophisticated? May require some scripting, though? Like some of those 1760 records are being deprecated, some are edits, and some are new features? Are there any other useful stats we could gather?

**Comment by stepps00** [comment]
IMO since the neighbourhood shapes mostly align with "official" boundaries for these districts, we should keep these shapes as is.. but the land water could be cut out from any neighbourhood/county shape and the remainder could be added with a `land` use in the alt name (kind of like this SF alt: https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/859/225/83/85922583-alt-mapzen-land.geojson)

That being said, I will merge these changes as-is and we can do some of that work as a follow up if we'd like.. I'd just need to investigate what these bodies of water are.

And for the total counts.. it would require some amount of scripting, but it's possible. Maybe PRs could start including (?):

- Number of total updated records
- Number of new records per placetype
- Number of records updated per placetype

**Comment by nvkelso** [comment]
Makes sense, thanks.

**Comment by nikosGeography** [comment]
Hi, great work guys keep it up. Where can I download the New locality extent (or the Updated neighbourhood records)? I went to whosonfirst-data-admin-tr/data/ but from there it's getting hard to find the neighbourhoods of Istanbul. Could you point me to the right direction? Many thanks.

**Comment by nvkelso** [comment]
Great question. We now offer two ways to download the data in common GIS formats.

1. Direct downloads from our partner https://geocode.earth/data/whosonfirst/ and follow the "TR" link in list of country codes. That'll show the original SQLite download option, as well as new shapefile option.

2. In qGIS install a plugin and download from application menu: https://plugins.qgis.org/plugins/HCMGIS/

Hope that helps!

**Pull request merged**
